### ISSUE TITLE
local planner todo's

### ISSUE THREAD

**Issue by tstastny** [tstastny/ACADOscripts#8]
- [x] gradient check for symmetric obstacles >> decision logic could be check current ground speed, then if GS also towing the line, check roll angle, then if roll allllso zero.. just choose right or left (make randomized? or just always right?)
    - not needed for now
- [x] try ray casting course dependent cost (how expensive is this?) >> otherwise should just include body-centric gridmap?
- [x] can we reduce the num of calculations necessary for objective jacobians? >> e.g. 1) replace some of them with analytic equations. 2) zero out known non-dependent jacobians w.r.t costs needing bilinear interpolation to avoid lots of extra needless calculations with nearest neighbors >> this will be super necessary if the above ray casting dependent cost is implemented..
- [x] need to put a check for if we are under terrain at any node and disable the triangle intersection checks .. otherwise the mpc is going to try and stay below the terrain 
- [x] reduce # of copies in objective eval by omitting OD from the "delta'd" input array
    - better solution.. use analytic jacobians
- [ ] get rid of second objective call .. needlessly doubling the function eval count
    - not for now.. maybe later.

**Comment by tstastny** [comment]
see #14
